---
- name: run_iptables_save
  ping: {}
  notify: run_iptables4_save 
  notify: run_iptables6_save 
    
- name: run_iptables4_save
  shell : "/usr/sbin/iptables-save > /etc/iptables/rules.v4"
  become: yes
  become_user: root 

- name: run_iptables6_save
  shell : "/usr/sbin/ip6tables-save > /etc/iptables/rules.v6"
  become: yes
  become_user: root 

- name: run_iptables6_save
  shell : "/usr/sbin/ip6tables-save > /etc/iptables/rules.v6"
  become: yes
  become_user: root 

- name: restart_apache2
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: apache2




